apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: febs
  labels:
    name: nginx
spec:
  volumes:
    - name: podpv
      persistentVolumeClaim:
        claimName: pvclaim
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
